# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dynamic:
    name: BuildAll
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build V Binary Search Tree
        uses: nzbr/vlang-action@v2
        with:
          file: binary_search_tree/binary_search_tree.v

      - name: Build V Hash Table
        uses: nzbr/vlang-action@v2
        with:
          file: hash_table/hash_table.v

      - name: Build V Hash Table
        uses: nzbr/vlang-action@v2
        with:
          file: hash_table/hash_table.v

      - name: Build V Linked List
        uses: nzbr/vlang-action@v2
        with:
          file: linked_list/linked_list.v

      - name: Build V FIFO Queue
        uses: nzbr/vlang-action@v2
        with:
          file: queue/queue.v

      - name: Build V LIFO Stack
        uses: nzbr/vlang-action@v2
        with:
          file: stack/stack.v

      - name: Build V Trie
        uses: nzbr/vlang-action@v2
        with:
          file: trie/trie.v

      - name: Build V binary search
        uses: nzbr/vlang-action@v2
        with:
          file: binary_search/binary_search.v

      - name: Build V selection sort
        uses: nzbr/vlang-action@v2
        with:
          file: selection_sort/selection_sort.v
